services:
  - type: web
    name: expense-tracker
    env: python
    buildCommand: |
     pip install -r requirements.txt
     flask db upgrade
     python -c "
     from app import app, db
     with app.app_context():
         db.session.execute('ALTER TABLE expense DROP COLUMN IF EXISTS category_id;')
         db.session.execute('DROP TABLE IF EXISTS category CASCADE;')
         db.session.commit()
     "    
	startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: expense-db
          property: connectionString

databases:
  - name: expense-db
    databaseName: expenses
    user: expense_admin
    plan: free
